version: "3.8"

services:
  watch_service:
    build:
      context: ./watch_service
    ports:
      - "8082:8082"
    environment:
      DATABASE_URL: "DATABASE_URL"
    env_file:
      - .env

  upload_service:
    build:
      context: ./upload_service
    depends_on:
      - watch_service
    ports:
      - "8080:8080"
    environment:
      AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID"
      AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY"
      AWS_BUCKET: "thesis-s3-bucket"
    env_file:
      - .env

  client:
    build:
      context: ./client
    depends_on:
      - watch_service
      - upload_service
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_UPLOAD_URL: http://upload_service:8080
      NEXT_PUBLIC_API_WATCH_URL: http://watch_service:8082
    env_file:
      - .env
